// export const ADD_VISITOR = "ADD_VISITOR";
// export const ADD_VISIT_DETAILS = "ADD_VISIT_DETAILS";
// export const CHECKOUT_VISITOR = "CHECKOUT_VISITOR";
export const CHECK_EXISTING_VISITOR = "CHECK_EXISTING_VISITOR";
export const ADD_VISITOR_REQUEST = "ADD_VISITOR_REQUEST";
export const ADD_VISITOR_SUCCESS = "ADD_VISITOR_SUCCESS";
export const ADD_VISITOR_FAILURE = "ADD_VISITOR_FAILURE";
export const ADD_VISIT_DETAILS_REQUEST = "ADD_VISIT_DETAILS_REQUEST";
export const ADD_VISIT_DETAILS_SUCCESS = "ADD_VISIT_DETAILS_SUCCESS";
export const ADD_VISIT_DETAILS_FAILURE = "ADD_VISIT_DETAILS_FAILURE";
export const CHECKOUT_VISITOR_REQUEST = "CHECKOUT_VISITOR_REQUEST";
export const CHECKOUT_VISITOR_SUCCESS = "CHECKOUT_VISITOR_SUCCESS";
export const CHECKOUT_VISITOR_FAILURE = "CHECKOUT_VISITOR_FAILURE";
export const CHECK_EXISTING_VISITOR_REQUEST = "CHECK_EXISTING_VISITOR_REQUEST";
export const CHECK_EXISTING_VISITOR_SUCCESS = "CHECK_EXISTING_VISITOR_SUCCESS";
export const CHECK_EXISTING_VISITOR_FAILURE = "CHECK_EXISTING_VISITOR_FAILURE";
export const FETCH_VISIT_DETAILS_FROM_DB_REQUEST =
  "FETCH_VISIT_DETAILS_FROM_DB_REQUEST";
export const FETCH_VISIT_DETAILS_FROM_DB_SUCCESS =
  "FETCH_VISIT_DETAILS_FROM_DB_SUCCESS";
export const FETCH_VISIT_DETAILS_FROM_DB_FAILURE =
  "FETCH_VISIT_DETAILS_FROM_DB_FAILURE";
// export const CHECKOUT_VISITOR = "CHECKOUT_VISITOR";
// export const FETCH_DATA_FROM_DB = "FETCH_DATA_FROM_DB";
// export const FETCH_VISITOR_DATA_FROM_DB = "FETCH_VISITOR_DATA_FROM_DB";
